@MetaheuristicsAPI_HostAddress = https://localhost:5111

POST {{MetaheuristicsAPI_HostAddress}}/test
Content-Type: application/json
[
    {
      "algorithm": "aoa",
      "n": 80,
      "i": 80,
      "fun": "rastrigin",
      "dim": 2,
      "parameters": null
    }
]
###

GET {{MetaheuristicsAPI_HostAddress}}/algorithms

###

@algorithm=string
GET {{MetaheuristicsAPI_HostAddress}}/algorithms/params/{{algorithm}}

###

GET {{MetaheuristicsAPI_HostAddress}}/functions

###
GET {{MetaheuristicsAPI_HostAddress}}/reports/paths

###
