@MetaheuristicsAPI_HostAddress = https://localhost:5111

POST {{MetaheuristicsAPI_HostAddress}}/test
Content-Type: application/json
{
  "algorithm": "aoa",
  "n": 80,
  "i": 80,
  "fun": "rastrigin",
  "dim": 2,
  "domain": null,
  "parameters": null
}
###
